default['mysql']['username'] = 'username'
default['mysql']['password'] = 'password'
default['mysql']['database']['dev'] = 'wordpress_dev'
default['mysql']['database']['stg'] = 'wordpress_stg'
default['mysql']['database']['prod'] = 'wordpress_prod'
default['mysql']['database']['test'] = 'wordpress_test'